jdbc.url=${ONTOP_DB_URL}
jdbc.driver=org.mariadb.jdbc.Driver
jdbc.user=${ONTOP_DB_USER}
jdbc.password=${ONTOP_DB_PASSWORD}

ontop.enableTestMode=false
ontop.query.defaultTimeout = 30
ontop.executionMode=virtual
